/*
 * Proj: srm-display-info example
 *
 * Auth: Eduardo Hopperdietzel
 *
 * Desc: This small utility displays the GPU configuration
 *       generated by SRM, along with its corresponding
 *       resources information.
 */

#include <SRMCore.h>
#include <SRMDevice.h>
#include <SRMListener.h>
#include <SRMCrtc.h>
#include <SRMEncoder.h>
#include <SRMPlane.h>
#include <SRMConnector.h>
#include <SRMConnectorMode.h>
#include <SRMLog.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>

using namespace SRM;

static int openRestricted(const char *path, int flags, void *)
{
    // Here something libseat could be used instead
    return open(path, flags);
}

static void closeRestricted(int fd, void *)
{
    close(fd);
}

SRMInterface srmInterface
{
    .openRestricted = &openRestricted,
    .closeRestricted = &closeRestricted
};

void deviceCreatedEvent(SRMListener *, SRMDevice *device)
{
    SRMLog::debug("DRM device (GPU) created: %s.", device->name());
}

void deviceRemovedEvent(SRMListener *, SRMDevice *device)
{
    SRMLog::debug("DRM device (GPU) removed: %s.", device->name());
}

void connectorPluggedEvent(SRMListener *, SRMConnector *connector)
{
    SRMLog::debug("DRM connector plugged (%d): %s.",
                  connector->id(),
                  connector->model());
}

void connectorUnpluggedEvent(SRMListener *, SRMConnector *connector)
{
    SRMLog::debug("DRM connector unplugged (%d): %s.",
                  connector->id(),
                  connector->model());
}

int main(void)
{
    setenv("SRM_DEBUG", "4", 1);

    SRMCore *srm = SRMCore::createSRM(&srmInterface);

    if (!srm)
    {
        SRMLog::fatal("Failed to initialize SRM.");
        return 1;
    }

    // Subscribe to DRM events
    SRMListener *deviceCreatedListener = srm->addDeviceCreatedListener(&deviceCreatedEvent);
    SRMListener *connectorPluggedListener = srm->addConnectorPluggedListener(&connectorPluggedEvent);

    printf("Allocator Device: %s\n", srm->allocatorDevice()->name());

    // Print devices information
    for (SRMDevice *device : srm->devices())
    {
        printf("Device: %s\n", device->name());

        printf("Client Caps:\n");
        printf("- STEREO 3D: %s\n",            device->clientCapStereo3D()             ? "YES" : "NO");
        printf("- UNIVERSAL PLANES: %s\n",     device->clientCapUniversalPlanes()      ? "YES" : "NO");
        printf("- ATOMIC: %s\n",               device->clientCapAtomic()               ? "YES" : "NO");
        printf("- ASPECT RATIO: %s\n",         device->clientCapAspectRatio()          ? "YES" : "NO");
        printf("- WRITEBACK CONNECTORS: %s\n", device->clientCapWritebackConnectors()  ? "YES" : "NO");

        printf("Caps:\n");
        printf("- DUMB BUFFER: %s\n",          device->capDumbBuffer()                 ? "YES" : "NO");
        printf("- PRIME IMPORT: %s\n",         device->capPrimeImport()                ? "YES" : "NO");
        printf("- PRIME EXPORT: %s\n",         device->capPrimeExport()                ? "YES" : "NO");
        printf("- FB2 MODIFIERS: %s\n",        device->capAddFb2Modifiers()            ? "YES" : "NO");

        printf("Render:\n");
        printf("- IS RENDERER: %s\n",          device->isRenderer()                     ? "YES" : "NO");
        printf("- RENDERER DEVICE: %s\n",      device->rendererDevice()->name());
        printf("- RENDER MODE: %s\n",          getRenderModeString(device->renderMode()));

        printf("Crtcs:\n");

        for (SRMCrtc *crtc : device->crtcs())
            printf("- Crtc (%d)\n", crtc->id());

        printf("Encoders:\n");

        for (SRMEncoder *encoder : device->encoders())
        {
            printf("- Encoder (%d): [", encoder->id());

            for (SRMCrtc *crtc : encoder->crtcs())
            {
                if (crtc == encoder->crtcs().back())
                    printf("%d]\n", crtc->id());
                else
                    printf("%d, ", crtc->id());
            }
        }

        printf("Planes:\n");

        for (SRMPlane *plane : device->planes())
        {
            printf("- Plane (%d):\n\t- Type: %s\n\t- Crtcs: [", plane->id(), getPlaneTypeString(plane->type()));

            for (SRMCrtc *crtc : plane->crtcs())
            {
                if (crtc == plane->crtcs().back())
                    printf("%d]\n", crtc->id());
                else
                    printf("%d, ", crtc->id());
            }
        }

        printf("Connectors:\n");

        for (SRMConnector *connector : device->connectors())
        {
            printf("- Connector (%d):\n", connector->id());
            printf("\tConnected: %s\n", connector->connected() ? "YES" : "NO");
            printf("\tStatus: %s\n", getConnectorStateString(connector->state()));
            printf("\tName: %s\n", connector->name());
            printf("\tModel: %s\n", connector->model());
            printf("\tManufacturer: %s\n", connector->manufacturer());
            printf("\tPhysical Size: %dx%d mm\n", connector->mmWidth(), connector->mmHeight());

            printf("\tEncoders: [");

            for (SRMEncoder *encoder : connector->encoders())
            {
                if (encoder == connector->encoders().back())
                    printf("%d]\n", encoder->id());
                else
                    printf("%d, ", encoder->id());
            }

            printf("\tModes:\n");

            for (SRMConnectorMode *connectorMode : connector->modes())
            {
                printf("\t - %dx%d@%dHz\n", connectorMode->width(), connectorMode->height(), connectorMode->refreshRate());
            }
        }

    }

    while (1)
    {
        // Poll DRM devices/connectors hotplugging events (0 disables timeout)
        if (srm->processMonitor(-1) < 0)
            break;
    }

    // Unsuscribe to DRM events
    delete deviceCreatedListener;
    delete connectorPluggedListener;

    return 0;
}
